blank_issues_enabled: true
contact_links:
  - name: eightblock Discussions
    url: https://github.com/eightblock-dev/eightblock/discussions
    about: Ask questions and share ideas with the community.
